spring:
  application:
    name: vn.emp.gateway
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  config:
    import: optional:configserver:${SPRING_CLOUD_CONFIG_URL:http://localhost:8888}
  cloud:
    config:
      fail-fast: true
      name: ${SPRING_CLOUD_CONFIG_NAME:vn.emp.gateway, common}
logging:
  level:
    root: DEBUG
