server:
  port: ${SERVER_PORT:8065}
  servlet:
    context-path: ${CONTEXT_PATH:/}
logging:
  #  config: classpath:logback-spring.xml
  level:
    com:
      zaxxer:
        hikari: DEBUG
        hikari.HikariConfig: DEBUG
spring:
  datasource:
    url: ${POSTGRES_DATASOURCE_URL:jdbc:postgresql://localhost:5432/emp?useUnicode=yes&characterEncoding=UTF-8&serverTimezone=Asia/Ho_Chi_Minh}
    username: ${POSTGRES_USERNAME:postgres}
    password: ${POSTGRES_PASSWORD:123456}
    hikari:
      maximum-pool-size: 20
      minimum-idle: 2
      connection-timeout: 30000
      connection-test-query: select 1
      schema: emp
  main:
    allow-bean-definition-overriding: true
  jpa:
    open-in-view: false
    generate-ddl: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: ${JPA_HIBERNATE_DDL_AUTO:validate}
      use-new-id-generator-mappings: false
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  jackson:
    time-zone: Asia/Ho_Chi_Minh
    serialization:
      FAIL_ON_EMPTY_BEANS: false
