CREATE TABLE hrm.hrm_business_unit (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	code varchar(50) NOT NULL,
	"name" varchar(255) NOT NULL,
	description text NULL,
	status numeric(2) NOT NULL,
	create_time timestamp(6) NOT NULL,
	create_by varchar(255) NOT NULL,
	update_time timestamp(6) NULL,
	update_by varchar(255) null,
	CONSTRAINT hrm_business_unit_id_pk PRIMARY KEY (id)
);

CREATE TABLE hrm.hrm_organization (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	parent_id int8 NULL,
	business_unit_id int8 NULL,
	"type" numeric(2) NOT NULL,
	code varchar(50) NOT NULL,
	"name" varchar(255) NOT NULL,
	head_unit_id int8 NULL,
	province_code varchar(20) NULL,
	district_code varchar(20) NULL,
	commune_code varchar(20) NULL,
	description text NULL,
	prev_id int8 NULL,
	status numeric(2) NOT NULL,
	create_time timestamp(6) NOT NULL,
	create_by varchar(255) NOT NULL,
	update_time timestamp(6) NULL,
	update_by varchar(255) NULL,
	phone_number varchar(50) NULL,
	address varchar(255) null,
	CONSTRAINT hrm_organization_id_pk PRIMARY KEY (id),
	CONSTRAINT hrm_organization_business_unit_id_fk FOREIGN KEY (business_unit_id) REFERENCES hrm.hrm_business_unit(id)
);

CREATE INDEX hrm_organization_business_unit_id_idx ON hrm.hrm_organization(business_unit_id);
