server:
  port: ${SERVER_PORT:8060}
  servlet:
    context-path: ${CONTEXT_PATH:/auth}
spring:
  application:
    name: vn.tmh.emp.auth
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  config:
    import: optional:configserver:${SPRING_CLOUD_CONFIG_URL:http://localhost:8888}
  cloud:
    config:
      fail-fast: true
      name: ${SPRING_CLOUD_CONFIG_NAME:vn.tmh.emp.auth}

